namespace: insert-project-name

data_container:
    image: a-data-container-name

worker_container:
    image: the-runtime-container-name
    config_tpl: behat-worker.yml.tpl

client_container:
    image: the-runtime-container-name
    config_tpl: behat-client.yml.tpl


